# Generated by Django 5.2.4 on 2025-07-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='emotion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
